env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  import/no-duplicates: 0