name: linter
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          make install
      - name: lint
        run: |
          make lint
      - name: lint
        run: |
          make test-coverage